version: "3.6"

networks:
  splunk-network:
    name: splunk-network
    external: true

services:
  splunk:
    image: splunk/universalforwarder:latest
    container_name: forwarder
    hostname: forwarder
    restart: unless-stopped
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=splunksplunk
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - splunk-network
    ports:
      - 9997:9997