version: "3.6"

networks:
  splunk-network:
    name: splunk-network

volumes:
  splunk-etc:
    name: splunk-etc
  splunk-var:
    name: splunk-var

services:
  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    hostname: splunk
    restart: unless-stopped
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=splunksplunk
    volumes:
      - splunk-var:/opt/splunk/var
      - splunk-etc:/opt/splunk/etc
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - splunk-network
    ports:
      - 8000:8000
      - 9997:9997
